### ISSUE TITLE
Nefunguje select Invoces z parametrem

### ISSUE THREAD

**Issue by dexcz** [ridercz/Fakturoid-API#13]
Dobrý den,

Děkuji za výbornou knihovnu, ale mám trošku problem. Pokud dělám select Invoces z parametrem 
například contextFak.Invoices.Select(page, InvoiceTypeCondition.Any, InvoiceStatusCondition.Overdue).ToList(), ta vrací to všechní statusy, místo Overdue

Děkuji

**Comment by ridercz** [comment]
Opraveno ve 2.10.0
