### ISSUE TITLE
JsonInvoice.subject_custom_id vs JsonSubject.custom_id

### ISSUE THREAD

**Issue by zachy** [ridercz/Fakturoid-API#18]
Třída JsonInvoice.subject_custom_id je typu int,
Třída JsonSubject.custom_id je typu string.

Vytvoříme-li nový subjekt bez custom_id nebo s nečíselnou hodnotou a dále mu vytvoříme fra, bude select padat na serializaci.

Viz DemoApp

**Comment by zachy** [comment]
Testováno na 2.11.0

**Comment by ridercz** [comment]
Opraveno ve verzi 2.11.1. Díky.
