### ISSUE TITLE
Možnost přidání tagů k faktuře

### ISSUE THREAD

**Issue by marek-benes** [ridercz/Fakturoid-API#4]
Fakturoid umožňuje ke každé faktuře přidat seznam tagů (_tags_ - nepovinné) a dále s nimi pracovat. Tohle, bohužel, _Fakturoid.Client_ neumožňuje. Bylo by možné rozšířit _JsonInvoice_ o pole tagů (v kódu je to označeno jako  _// TODO pole `tags` - dle webové dokumentace je typu "array"_)?

**Comment by ridercz** [comment]
Fixed in commit 03c598fe0361f1c117e712278c48572d3a7fc827
